[remote.bindings]
3 = "volume_up"
1 = "volume_down"
2 = "pause"
c = "b1"
f = "b2"
b = "b3"
e = "b4"
a = "b5"
d = "b6"

[remote.keys.volume_up]
method = "volume_up"
params = "15"

[remote.keys.volume_down]
method = "volume_down"
params = "15"

[remote.keys.b1]
method = "url"
params = [
  "https://cdn.jmvstream.com/w/LVW-9716/LVW9716_HbtQtezcaw/playlist.m3u8"  # TV Aparecida
]

[remote.keys.b2]
method = "youtube"
params = [
    "En_Qi8vcpsQ",  # Roberto Carlos Especial 2024
    "OZJyo2c1vQU",  # Julio Iglesias
    "ujUaIXcQh9Y",  # Caetano Veloso
    "YdMn8xzCOS0",  # Gilberto Gil
    "_mDTJzZ9900",  # Francisco José - Olhos Castanhos
    "4KyO37n8Mr4",  # Francisco José - Nem às parede confesso
    "nE8uwamKfdY",  # Francisco José - A noite de meu bem
    "i7j0bw5TonI"   # Roupa Nova - 40 anos

    #"90J-t4S_K0E",  # Erasmo Carlos
]

[remote.keys.b3]
method = "youtube"
params = [
    "2ENqKaIa78I",  # Alter do Chão
    "LojAwU1HCV8",  # 10 coisas no Brasil
    "8OxBxgmIh6o",  # Serra da Capivara
    "F01ciDMSJtA",  # Fernando de Noronha
    "Q_fhu4Ckh5c",  # Salto Angel
    "eH3vK1Be3CM",  # RRuas em Fernando de Noronha
    "uKwxuE_DulQ"  # Ceará
]

[remote.keys.b4]
method = "youtube"
params = [
    "6LPIXiguKaQ",  # RRuas em Lisboa e Beja
    "Sq0L09PfBuA",  # RRuas em Mostar
    "fspUhP4a6bM",  # RRuas em Edimburgo
    "zdExsFnqWI4",  # RRuas em Istambul
    "e1oFGA5WiVc",  # RRuas em Roma
    "esfa9wwsYwU",  # RRuas na Antártida
    "oGuWwMszSFI",  # RRuas em Veneza
    "T695eiB-kX4",  # RRuas no Templo de Isis Egito
    "aq_be_TFeZM",  # RRuas em Jerusalém
    "TsYYnL1WvRU",  # RRuas em Capadócia
    "D_AVORG9lZg",  # Rolê Família - Marrakesh
    "-0LS4X9CPpo"   # Rolê Família - Saara
]
